package com.form.org.exception;


public enum ErrorCodes {
	ANALYSE_MEDICAL_NOT_FOUND(100),
	ANALYSE_MEDICAL_NOT_VALID(101),
	
	BIOLOGISTE_NOT_FOUND(200),
	BIOLOGISTE_NOT_VALID(201),
	
	DEPARTEMENT_NOT_FOUND(300),
	DEPARTEMENT_NOT_VALID(301),
	
	DETAIL_RESULTAT_NOT_FOUND(400),
	DETAIL_RESULTAT_NOT_VALID(401),
	
	FACTURE_NOT_FOUND(500),
	FACTURE_NOT_VALID(501),
	
	PATIENT_NOT_FOUND(600),
	PATIENT_NOT_VALID(601),
	
	PRELEVEUR_NOT_FOUND(700),
	PRELEVEUR_NOT_VALID(701),

	PROFIL_NOT_FOUND(800),
	PROFIL_NOT_VALID(801),
	
	RESERVATION_NOT_FOUND(900),
	RESERVATION_NOT_VALID(901),
	
	TYPE_ANALYSE_NOT_FOUND(1000),
	TYPE_ANALYSE_NOT_VALID(1001),
	
	UTILISATEUR_NOT_FOUND(1100),
	UTILISATEUR_NOT_VALID(1101),
	;
		
	private int code;
	
 ErrorCodes(int code) {
	 this.code=code;
	}
 
 public int getCode() {
	 return code;
 }

}
